### ISSUE TITLE
[FEATURE] FE_홈

### ISSUE THREAD

**Issue by JackAhn** [Diving-Seagull/With-u#13]
## 기능 설명 
    홈 화면 관련 기능들을 구현합니다.
     
## TODO
- [x] 홈 화면 레이아웃 디자인
- [x] 유저 데이터 출력
- [x] 현재 일정 출력
- [x] 최신 공지사항 출력
